# Generated by Django 3.0.6 on 2020-08-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200807_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reading',
            field=models.CharField(choices=[('5 minutes', '5 Minutes'), ('10 minutes', '10 Minutes'), ('20 minutes', '20 Minutes'), ('30 minutes', '30 Minutes')], default='5 minutes', max_length=20),
        ),
    ]
